### ISSUE TITLE
[BUG REPORT] v2.wallet.pokt.network is broken

### ISSUE THREAD

**Issue by ArtSabintsev** [pokt-foundation/wallet#414]
**Describe the bug**

**To Reproduce**
1. Go to v2.wallet.pokt.network
2. Balance isn't visible

**Expected behavior**
Balance should be visible 

**Additional context**
This broke during the migration since the endpoint for v2.wallet is probably an old one.

**Comment by ArtSabintsev** [comment]
@kutoft this was addressed, right?

**Comment by PseudoMera** [comment]
Yes, it was addressed.
