### ISSUE TITLE
Changes for Ledger

### ISSUE THREAD

**Issue by ArtSabintsev** [pokt-foundation/wallet#421]
# From Nate at Obsidian Systems via Victor from Ledger:

## Use newer logo on import account 

Replace:
<img width="203" alt="Screenshot_2023-06-08_at_3 31 45_PM" src="https://github.com/pokt-foundation/wallet/assets/854860/c5a6ec2d-452e-4270-8df2-40f1aa42030b">

With these two: 
<img width="239" alt="Screenshot_2023-06-08_at_3 33 43_PM" src="https://github.com/pokt-foundation/wallet/assets/854860/60f83d99-faa4-4473-9dd9-9f618150d1e9">

<img width="266" alt="Screenshot_2023-06-08_at_3 33 50_PM" src="https://github.com/pokt-foundation/wallet/assets/854860/571d026c-4eb6-415f-ad95-61431d82b569">

## Add "Verify address" button
There are two address related commands that the Ledger app respond to. https://github.com/obsidiansystems/ledger-app-pocket/blob/develop/docs/apdu.md

`GET_PUBKEY` is used in your wallet already. During the "Import Account" the wallet polls the Ledger app for the first 5 addresses (or more if requested). This view is the result of that interaction:
<img width="893" alt="Screenshot_2023-06-08_at_3 24 38_PM" src="https://github.com/pokt-foundation/wallet/assets/854860/6be8d2aa-520a-41dc-82b6-7e7b4fcd8102">

He is requesting an additional button in your wallet (after import) that will use VERIFY_ADDRESS instead. The difference between the two is that the "verify" version prompts the user after displaying the address on the device. I suggest this new button replace "Export Keyfile" shown here as it is unused/non-functional: 
Image
<img width="865" alt="Screenshot_2023-06-08_at_3 24 58_PM" src="https://github.com/pokt-foundation/wallet/assets/854860/d4538b49-35cc-4827-8159-b0551ab11dae">

## Log Out on Top Right Corner
This button is non-functional

**Comment by PseudoMera** [comment]
Fixed in [#feat: update ledger](https://github.com/pokt-foundation/wallet/commit/dca15f8f146178ab9fb44c49167306be5710caf6)
