### ISSUE TITLE
Wallet Staking Page goes blank when "Select Chains" Box is clicked. [Regional Issue]

### ISSUE THREAD

**Issue by crabmanpokt** [pokt-foundation/wallet#422]
Depending on the region the supportedChains API may either return ["0001","0003"...] or  "["0001","0003"...]" , the latter does not work the former does

This fix it to this will also not work
 https://github.com/pokt-foundation/wallet/pull/418

**Comment by crabmanpokt** [comment]
Fix: https://github.com/pokt-foundation/wallet/pull/423

**Comment by PseudoMera** [comment]
Code has been merged, closing this issue.

Thanks!
